import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Leaf, Sparkles } from 'lucide-react';
import { books, categories, testimonials } from '@/lib/data';
import { formatPrice } from '@/lib/utils';
import { BookCard, BookCover } from '@/components/book-card';
import { Button, SectionHeading } from '@/components/ui';
import { MotionIn } from '@/components/motion-in';

export default function HomePage() {
  const featured = books.filter((book) => book.featured);
  return <main>
    <section className="paper-texture border-b border-line px-5 pb-14 pt-10 md:px-10 md:pb-20 md:pt-14"><div className="mx-auto grid max-w-[1440px] items-center gap-10 lg:grid-cols-[.86fr_1.14fr]"><MotionIn className="max-w-xl"><h1 className="display-title max-w-[620px] text-[clamp(4.2rem,8vw,8.1rem)] leading-[.82]">Find your<br /><span className="text-wine">next chapter.</span></h1><div className="mt-10 h-px w-12 bg-wine" /><p className="mt-6 max-w-sm text-base leading-7 text-ink/65">A carefully chosen collection of books for curious minds, tender hearts, and the life you’re building.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/shop"><Button>Shop all books <ArrowRight size={16} className="ml-2" /></Button></Link><Link href="/categories"><Button variant="secondary">Browse by category</Button></Link></div></MotionIn><MotionIn delay={.12} className="relative lg:pl-8"><div className="relative min-h-[380px] overflow-hidden rounded-[1.5rem] bg-[#e8e5dd] p-5 md:min-h-[500px]"><div className="absolute right-[-4%] top-[-8%] h-[110%] w-[57%] rounded-full bg-[#d8d3c7] blur-[2px]" /><div className="absolute bottom-10 left-[10%] z-10 h-16 w-[72%] rotate-[-5deg] rounded bg-[#8f2d33] shadow-xl md:h-20"><p className="display-title px-6 pt-4 text-xl text-white md:text-2xl">A line in the world</p><span className="px-6 text-[10px] uppercase tracking-[.18em] text-white/60">Dorothy Whipple</span></div><div className="absolute bottom-28 left-[9%] z-20 h-16 w-[72%] rotate-[2deg] rounded bg-[#e5ded0] shadow-xl md:h-20"><p className="display-title px-6 pt-4 text-xl text-ink md:text-2xl">The cartographers</p><span className="px-6 text-[10px] uppercase tracking-[.18em] text-ink/55">Peng Shepherd</span></div><div className="absolute bottom-46 left-[13%] z-30 h-16 w-[67%] rotate-[-2deg] rounded bg-[#3f5a46] shadow-xl md:h-20"><p className="display-title px-6 pt-4 text-xl text-white md:text-2xl">Small kin</p><span className="px-6 text-[10px] uppercase tracking-[.18em] text-white/60">Claire Louise Bennett</span></div><div className="absolute bottom-64 left-[18%] z-40 h-16 w-[60%] rotate-[1deg] rounded bg-[#191918] shadow-xl md:h-20"><p className="display-title px-6 pt-4 text-xl text-white md:text-2xl">The wild observer</p><span className="px-6 text-[10px] uppercase tracking-[.18em] text-white/60">Jane Alden</span></div><div className="absolute bottom-82 left-[23%] z-50 h-16 w-[52%] rotate-[-1deg] rounded bg-[#f4f0e7] shadow-xl md:h-20"><p className="display-title px-6 pt-4 text-xl text-ink md:text-2xl">The everyday practice</p><span className="px-6 text-[10px] uppercase tracking-[.18em] text-ink/55">Sophie Nelson</span></div><div className="absolute bottom-5 right-6 z-50 flex items-center gap-2 text-xs text-ink/50"><Leaf size={14} /> Made for slow browsing</div></div></MotionIn></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-16 md:px-10 md:py-24"><SectionHeading title="Featured books" copy="New favourites, enduring classics, and the ones we keep handing to friends." action={<Link href="/shop" className="text-sm font-semibold text-wine hover:underline">View all <ArrowUpRight size={15} className="inline" /></Link>} /><div className="mt-9 grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-3 md:gap-x-7 lg:grid-cols-5">{featured.map((book, i) => <MotionIn key={book.id} delay={i * .04}><BookCard book={book} /></MotionIn>)}</div></section>
    <section className="border-y border-line bg-linen px-5 py-16 md:px-10 md:py-24"><div className="mx-auto max-w-[1440px]"><SectionHeading title="For every kind of reader" copy="Start wherever you are. We’ll help you find your way through." /><div className="mt-10 grid gap-px overflow-hidden rounded-2xl bg-line sm:grid-cols-2 lg:grid-cols-3">{categories.map((category, i) => <Link href={`/shop?category=${encodeURIComponent(category.name)}`} key={category.name} className="group flex min-h-[180px] flex-col justify-between bg-linen p-6 transition hover:bg-white md:p-8"><div className="flex items-start justify-between"><span className="display-title text-3xl">0{i + 1}</span><ArrowUpRight size={18} className="text-ink/35 transition group-hover:translate-x-1 group-hover:-translate-y-1 group-hover:text-wine" /></div><div><h3 className="display-title text-2xl">{category.name}</h3><p className="mt-1 text-sm text-ink/55">{category.note}</p></div></Link>)}</div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-16 md:px-10 md:py-24"><div className="grid items-center gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><SectionHeading eyebrow="Staff pick" title="A book for the life you’re in." copy="The best recommendations feel a little like being understood. This month, our team is reading The Everyday Practice." /><Link href="/book/the-everyday-practice" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-wine hover:underline">Read the note <ArrowRight size={16} /></Link></div><Link href="/book/the-everyday-practice" className="group grid grid-cols-[.7fr_1fr] items-center gap-6 rounded-2xl bg-[#e8e5dd] p-6 md:gap-12 md:p-12"><div className="max-w-[220px]"><BookCover book={books[0]} large /></div><div><p className="mb-6 text-[11px] font-semibold uppercase tracking-[.2em] text-wine">The note</p><p className="display-title text-3xl leading-tight md:text-5xl">“A gentle nudge back toward the days that feel like yours.”</p><p className="mt-7 text-sm text-ink/55">— Mara, ChapterOne bookseller</p></div></Link></div></section>
    <section className="bg-ink px-5 py-16 text-white md:px-10 md:py-24"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[.6fr_1.4fr]"><div><p className="mb-4 text-[11px] font-semibold uppercase tracking-[.2em] text-[#e59b91]">Author spotlight</p><h2 className="display-title text-5xl leading-[.9] md:text-7xl">Meet the<br />mind behind<br /><span className="text-[#e59b91]">Small Kin.</span></h2><Link href="/shop?author=claire-louise-bennett" className="mt-8 inline-flex items-center gap-2 text-sm text-white/75 hover:text-white">Explore Claire’s books <ArrowUpRight size={16} /></Link></div><div className="flex flex-col justify-end"><div className="mb-8 h-px bg-white/20" /><p className="max-w-2xl text-2xl leading-tight text-white/80 md:text-4xl">“Her work explores memory, place, and the quiet strangeness of everyday life.”</p><div className="mt-10 flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#e59b91] text-ink"><Sparkles size={19} /></div><div><p className="text-sm font-semibold">Claire Louise Bennett</p><p className="text-xs text-white/45">Novelist, essayist, keen observer</p></div></div></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-16 md:px-10 md:py-24"><SectionHeading title="The good word" copy="A few notes from readers who found something worth keeping." /><div className="mt-10 grid gap-4 md:grid-cols-3">{testimonials.map((item) => <figure key={item.name} className="border-l border-wine pl-5"><blockquote className="display-title text-2xl leading-tight">“{item.quote}”</blockquote><figcaption className="mt-6 text-xs uppercase tracking-[.14em] text-ink/50">{item.name} · {item.detail}</figcaption></figure>)}</div></section>
    <section className="mx-5 rounded-2xl bg-[#e8e5dd] px-6 py-14 md:mx-10 md:px-12 md:py-20"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="mb-4 text-[11px] font-semibold uppercase tracking-[.2em] text-wine">The reading list</p><h2 className="display-title max-w-2xl text-5xl leading-[.9] md:text-7xl">A little more<br />good stuff.</h2><p className="mt-5 max-w-md text-sm leading-6 text-ink/65">New books, thoughtful recommendations, and small reasons to make time for reading.</p></div><Link href="/contact" className="inline-flex items-center gap-2 text-sm font-semibold text-wine hover:underline">Join our community <ArrowRight size={16} /></Link></div></section>
  </main>;
}
