'use client';

import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { ArrowUpRight, BookOpen, Heart, Menu, Search, ShoppingBag, UserRound, X } from 'lucide-react';
import { useState } from 'react';
import { useCart } from './cart-provider';
import { Button } from './ui';

const nav = [['Shop', '/shop'], ['Categories', '/categories'], ['About', '/about'], ['FAQ', '/faq']];

export function SiteHeader() {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const router = useRouter(); const pathname = usePathname(); const { count } = useCart();
  function submit(event: React.FormEvent) { event.preventDefault(); if (query.trim()) router.push(`/search?q=${encodeURIComponent(query)}`); }
  return <header className="sticky top-0 z-40 border-b border-line bg-white/95 backdrop-blur"><div className="mx-auto flex h-[72px] max-w-[1440px] items-center justify-between gap-5 px-5 md:px-10"><Link href="/" className="display-title whitespace-nowrap text-2xl tracking-[-.06em]">ChapterOne <span className="text-wine">Books</span></Link><nav className="hidden items-center gap-7 lg:flex">{nav.map(([label, href]) => <Link key={href} href={href} className={`text-sm transition-colors hover:text-wine ${pathname === href ? 'text-wine' : 'text-ink/75'}`}>{label}</Link>)}</nav><div className="flex items-center gap-3"><form onSubmit={submit} className="hidden items-center gap-2 rounded-full border border-ink/20 px-3 py-2 md:flex"><Search size={15} className="text-ink/50" /><input value={query} onChange={(e) => setQuery(e.target.value)} aria-label="Search books" placeholder="Search books" className="w-28 bg-transparent text-xs outline-none placeholder:text-ink/45" /></form><Link href="/wishlist" aria-label="Wishlist" className="hidden p-2 text-ink/70 hover:text-wine sm:block"><Heart size={18} strokeWidth={1.7} /></Link><Link href="/dashboard" aria-label="Account" className="hidden p-2 text-ink/70 hover:text-wine sm:block"><UserRound size={18} strokeWidth={1.7} /></Link><Link href="/cart" className="relative flex items-center gap-2 p-2 text-sm hover:text-wine"><ShoppingBag size={18} strokeWidth={1.7} /><span className="hidden sm:inline">Cart</span>{count > 0 && <span className="flex h-5 min-w-5 items-center justify-center rounded-full bg-wine px-1 text-[10px] font-bold text-white">{count}</span>}</Link><button className="p-2 lg:hidden" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X size={20} /> : <Menu size={20} />}</button></div></div>{open && <div className="border-t border-line bg-white px-5 py-5 lg:hidden"><form onSubmit={submit} className="mb-4 flex items-center gap-2 border-b border-line pb-3"><Search size={16} /><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search books" className="w-full bg-transparent text-sm outline-none" /></form><div className="grid gap-4">{nav.map(([label, href]) => <Link onClick={() => setOpen(false)} key={href} href={href} className="display-title text-2xl">{label}</Link>)}<Link onClick={() => setOpen(false)} href="/dashboard" className="text-sm">My account <ArrowUpRight size={14} className="inline" /></Link></div></div>}</header>;
}

export function SiteFooter() { return <footer className="mt-24 bg-ink px-5 py-14 text-white md:px-10"><div className="mx-auto max-w-[1440px]"><div className="grid gap-12 border-b border-white/15 pb-14 lg:grid-cols-[1.3fr_1fr_1fr_1.2fr]"><div><Link href="/" className="display-title text-3xl tracking-[-.06em]">ChapterOne <span className="text-[#e59b91]">Books</span></Link><p className="mt-5 max-w-xs text-sm leading-6 text-white/55">Thoughtfully chosen books for curious lives. Based in South Africa, shipping everywhere.</p></div><div><p className="mb-5 text-[11px] font-semibold uppercase tracking-[.18em] text-white/40">Explore</p><div className="grid gap-3 text-sm text-white/70"><Link href="/shop">Shop all books</Link><Link href="/categories">Browse categories</Link><Link href="/about">Our story</Link><Link href="/faq">FAQs</Link></div></div><div><p className="mb-5 text-[11px] font-semibold uppercase tracking-[.18em] text-white/40">Account</p><div className="grid gap-3 text-sm text-white/70"><Link href="/dashboard">My account</Link><Link href="/wishlist">Wishlist</Link><Link href="/cart">Cart</Link><Link href="/contact">Contact us</Link></div></div><div><p className="mb-5 text-[11px] font-semibold uppercase tracking-[.18em] text-white/40">The reading list</p><p className="mb-4 text-sm leading-6 text-white/55">New books, good ideas, and a little quiet in your inbox.</p><NewsletterForm /></div></div><div className="flex flex-col justify-between gap-3 pt-5 text-xs text-white/40 md:flex-row"><span>© 2026 ChapterOne Books</span><span>Made for readers, with care.</span></div></div></footer> }

function NewsletterForm() { const [email, setEmail] = useState(''); const [done, setDone] = useState(false); async function submit(e: React.FormEvent) { e.preventDefault(); if (!email) return; await fetch('/api/newsletter', { method: 'POST', body: JSON.stringify({ email }) }); setDone(true); } return done ? <p className="text-sm text-[#e59b91]">You’re on the list. Thank you.</p> : <form onSubmit={submit} className="flex border-b border-white/30 pb-2"><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Your email address" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-white/40" /><Button type="submit" variant="ghost" className="text-white hover:text-[#e59b91]">Join <ArrowUpRight size={15} className="ml-1" /></Button></form>; }
